export const GOAL = '/goal'
export const PERSONAS = '/personas'
export const SKETCHES = '/sketches'
export const CRITIQUE = '/critique'
export const TECHNOLOGIES = '/technologies'
export const SMART_WOD_HOME = '/smart-wod-home'
export const SMART_WOD_BUILD_ONE = '/smart-wod-build'
