import React, { Component } from 'react'
import CollapsibleText from '../../component/collapsable-text/index'


export default class Goal extends Component {
  render() {
    return (
      <div>
        <h2>Goal</h2>
        <p>To help the user generate and track workouts, whether at a fully kitted-out gym or home with minimal equipment, regardless of fitness level. The Covid-19 pandemic, has seen an increase in people wanting to stay fit and healthy but do not know where or how to start, without necessarily having access to gym equipment, coaches or a fitness tracker.</p>
        <p>The ‘Bear Fitness’ app will help to generate customised workouts, based on the following variables, either user selected or autogenerated by the app:</p>

        <p className='mt2'>Muscle Groups -  the user has selected to train:</p>
        <ul>
          <li>Upper body – e.g. biceps, triceps, deltoids, etc.</li>
          <li>Lower body – e.g. glutes, calves, quads, etc.</li>
          <li>Core – e.g. abs, obliques, lower back, etc.</li>
          <li>Full body – a combination of the above.</li>
        </ul>

        <p className='mt2'>Type – the user selects to complete:</p>
        <ul>
          <li>Endurance -  e.g.  Running, Biking, Rowing, Walking, etc.</li>
          <li>Strength – e.g. Bench Press, Squats, Push Ups, etc.</li>
          <li>Mixture of both – a combination of the above.</li>
        </ul>

        <p className='mt2'>Style – auto generated by the app:</p>
        <ul>
          <li>Rounds for time: completing the required workout a specified number of times in the lowest time possible</li>
          <li>AMRAP: as many rounds of the workout as possible, in the specified time</li>
          <li>Tabata: as specified number of rounds, completed in blocks or workouts and rest</li>
          <li>EMOM: for a specified amount of time, complete as much of the workout as possible in a minute, before restarting for the next minute.</li>
        </ul>

        <p className='mt2'>Level - determines the number of workout sets, reps per set and overall workout time, the user selects to complete:</p>
        <ul>
          <li>Easy – for example: two sets, 10 reps each set, with a workout time of 20 minutes</li>
          <li>Medium – for example: three sets, 20 reps each set, with a workout time of 30 minutes</li>
          <li>Hard – for example: five sets, 50 reps each set, with a workout time of 60 minutes</li>
        </ul>

        <p className='mt2'>Equipment - the user has selected as having access to e.g. dumbbells, ab mat, resistance bands, etc. </p>

        <p className='mt2'>In addition, to generating workouts customised to the user, this app will also:</p>
        <ul>
          <li>Allow the user to save their favourite workouts, providing easy future access</li>
          <li>Access to an exercise library, which the user can use, generate and save their own workout</li>
          <li>Have a voice activated timer, to assist in more accurately tracking a user’s times</li>
          <li>Use geolocation to map a user’s run, cycle, etc. tracking their distance, route and average kmph/mph.</li>
        </ul>
      </div>
    )
  }
}
